name: Build and Test

on:
  push:
    branches: [ 'main' ]
  pull_request:
    branches: [ 'main' ]
  workflow_dispatch:

env:
  DOTNET_VERSION: '8.0.x'
  SOLUTION_FILE: 'PhaseShift.sln'

jobs:
  build:
    runs-on: windows-latest

    strategy:
      fail-fast: true
      matrix:
        configuration: [Debug, Release]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Create artifact directories
      run: |
        New-Item -ItemType Directory -Path artifacts/${{ matrix.configuration }}/build-output -Force
      
    - name: Restore dependencies
      run: dotnet restore ${{ env.SOLUTION_FILE }}

    - name: Build solution and capture logs
      run: dotnet build ${{ env.SOLUTION_FILE }} --no-restore --configuration ${{ matrix.configuration }} --verbosity normal | Tee-Object -FilePath artifacts/${{ matrix.configuration }}/build.log

    - name: Run unit tests and capture logs
      run: dotnet test ${{ env.SOLUTION_FILE }} --no-build --configuration ${{ matrix.configuration }} --verbosity normal --logger "trx;LogFileName=test-results.trx" | Tee-Object -FilePath artifacts/${{ matrix.configuration }}/test.log

    - name: Collect test results
      run: |
        Copy-Item -Path **/TestResults/*.trx -Destination artifacts/${{ matrix.configuration }}/test-results.trx -Force

    - name: Collect build output
      run: |
        Copy-Item -Path "PhaseShift.UI\bin\${{ matrix.configuration }}\net8.0-windows*" -Destination "artifacts/${{ matrix.configuration }}/build-output" -Recurse -Force

    - name: Upload bundled artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.configuration }}
        path: artifacts/${{ matrix.configuration }}
